CREATE SCHEMA system AUTHORIZATION "system";

SET search_path to system;

DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS CHATS;
DROP TABLE IF EXISTS CHAT_USERS;

CREATE TABLE CHAT_USERS (
  USER_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(100),
  EMAIL VARCHAR(100),
  PASSWORD VARCHAR(100)
);
CREATE UNIQUE INDEX USERS_EMAIL_IDX ON CHAT_USERS (LOWER(EMAIL));

CREATE TABLE CHATS (
  CHAT_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  CREATED_BY INTEGER NOT NULL REFERENCES CHAT_USERS (USER_ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX CHATS_NAME_IDX ON CHATS (LOWER(NAME));

CREATE TABLE MESSAGES (
  MESSAGE_ID BIGSERIAL PRIMARY KEY,
  CHAT_ID INTEGER NOT NULL REFERENCES CHATS (CHAT_ID) ON DELETE CASCADE,
  USER_ID INTEGER NOT NULL REFERENCES CHAT_USERS (USER_ID) ON DELETE CASCADE,
  MESSAGE VARCHAR(100) NOT NULL,
  CREATED TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);
