datasource:
  host: 192.168.99.100

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${datasource.host}:5432/ora-db
    username: system
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  header: Authorization
  secret: theSauceIsTheBoss
  tokenPrefix: Bearer
  expiration: 600000

logging:
  level:
    com.ora: DEBUG
    org.springframework: WARN
    org.springframework.jdbc.core: TRACE
    org.hibernate: WARN